### ISSUE TITLE
⚡️Add sensitive data types - Europe specific 

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#130]
# 💭 Introduction

Akto allows users to find sensitive params in request and response of APIs. These sensitive params include PII data such as SSN, Credit card number, phone number etc. You can check how it works in the [docs](https://docs.akto.io/api-inventory/sensitive-data).

Your task is to add `Europe specific` sensitive params.

###  👀 Impact

Your task will give users the ability to detect `Europe specific` sensitive data types.

###  🎯 Requirements

- Understanding of regex
- Understanding of unit test

### ✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Add regular expressions for below[ Europe related PII types](https://github.com/mmcatcd/pii-tool/blob/master/European%20RegEx.csv). Feel free to add your own too.
- [ ] Please provide the reference URL that mentions the nature of the number. 
- [ ] Add an entry in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json) file
- [ ] Add a test case entry in [TestFintechTypes.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java#L32)
- [ ] Submit a pull request here 

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by legendary0911** [comment]
I would like to work on this issue

**Comment by Ankita28g** [comment]
Hi @legendary0911 assigning this to you! Happy hackfesting 🎉

**Comment by SandeepSrinivasan** [comment]
is that only one person can be assigned to an issue ?
or 
Any one who submits the PR first ?

How it is calculated ?

**Comment by Ankita28g** [comment]
Hi @SandeepSrinivasan for this particular issue, multiple folks can work. Should I assign to you if you are interested?

**Comment by SandeepSrinivasan** [comment]
Sure please, love to work on this issue!

**Comment by SandeepSrinivasan** [comment]
hey @Ankita28g @ankush-jain-akto created a PR for this issue 

[https://github.com/akto-api-security/akto/pull/254](url)

**Comment by Ankita28g** [comment]
Hi @SandeepSrinivasan @legendary0911 thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by Ankita28g** [comment]
@SandeepSrinivasan Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by SandeepSrinivasan** [comment]
@Ankita28g submitted the Form
