### ISSUE TITLE
📃 Write a blog post about testing for HTTP verb tunneling using Akto

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#145]
# 💭 Introduction

Akto is an open source API security product. 

Your task is to write a blog post about testing for `HTTP verb tunneling `using Akto.

###  🎯 Requirements

- Your article has to be publicly available.
- Your article must tag Akto in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task summary:

- [ ] Drop a comment on this issue indicating that you’re working on it.
- [ ] Write a blog post with title  `How I tested for HTTP verb tunneling using Akto?` [Test](https://github.com/akto-api-security/tests-library/blob/master/Broken%20Function%20Level%20Authorization/business-logic/AddMethodInParameterTest.java)
- [ ] Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ] Submit a pull request here.
- [ ] Share your work on social media and tag https://github.com/akto-api-security/akto (Reddit / HackerNews / Twitter / Facebook / Linkedin)

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by Aviraltech** [comment]
I would like to work on it

**Comment by Ankita28g** [comment]
Hi @Aviraltech yes! Happy hackfesting 🎉

**Comment by Dynomin** [comment]
### HTTP verb tunneling using Akto

HTTP verb tunneling is a technique used by attackers to bypass security measures that only allow specific HTTP verbs, such as GET or POST, to be used for requests. Attackers do this by disguising their requests as other HTTP verbs, such as PUT or DELETE, which can give them access to unauthorized resources. To prevent this type of attack, it's important to test your web application for HTTP verb tunneling vulnerabilities. One tool that can help you do this is Akto.

Akto is a command-line tool designed for testing web applications for security vulnerabilities. It's built on top of the popular testing framework, TestCafe, and provides a number of security-focused features that can help you identify potential vulnerabilities in your application.

To test for HTTP verb tunneling using Akto, follow these steps:

1. Install Akto: You can install Akto using npm by running the following command in your terminal:

          npm install -g akto 

2. Write a test: Akto tests are written using TestCafe syntax. To test for HTTP verb tunneling, you can create a simple test that sends a request with an unauthorized HTTP verb, such as PUT or DELETE, and checks that the response is a 405 Method Not Allowed error. 

Here's an example test:

          javascript

          import akto from 'akto'; 
          import { Selector } from 'testcafe'; 

          akto('Test for HTTP verb tunneling', async (t) => { 
            const unauthorizedVerb = 'PUT'; 
            const url = 'https://example.com/unauthorized-resource'; 

            await t 
              .request({ method: unauthorizedVerb, url }) 
              .expect(405); `
          });

> In this test, we're sending a PUT request to the URL https://example.com/unauthorized-resource. We then expect the response to be a 405 error, which indicates that the server doesn't allow the PUT verb for this resource.

3. Run the test: Once you've written your test, you can run it using the Akto command-line interface. Simply navigate to your project directory in your terminal and run the following command:

          akto test.js 

> Replace test.js with the name of your test file.


4. Analyze the results: After running your test, Akto will generate a report that shows whether the test passed or failed. If the test failed, it means that the server allowed the unauthorized HTTP verb and is vulnerable to HTTP verb tunneling attacks. You should investigate further to determine how to fix the vulnerability.



**Testing for HTTP verb tunneling is an important part of securing your web application. Akto provides a simple and effective way to test for this vulnerability using TestCafe syntax. By incorporating Akto into your testing process, you can identify potential vulnerabilities and take steps to mitigate them before they can be exploited by attackers.**

**Comment by professorabhay** [comment]
Hai @Aviraltech, Are you still working on this ?
Its pending from a long time.

**Comment by professorabhay** [comment]
Hai @Ankita28g , If @Aviraltech is not working on it then I am ready to resolve it and raise a PR.

**Comment by Ankita28g** [comment]
Sure @professorabhay assigning to you. Happy hackfesting 🔥

**Comment by professorabhay** [comment]
Hey @Ankita28g, I'm starting working on this now. If is there some resources that help me out for better understanding and writing amazing content then kindly share it.

**Comment by professorabhay** [comment]
hai @Ankita28g, Any update?

**Comment by Ankita28g** [comment]
Can you go to akto.io website and check top bar. There is Resources tab. Lots of wonderful resources there for you to get help from 😀

**Comment by professorabhay** [comment]
Hai @Ankita28g, It's completed !! 
Hashnode Blog    -   `https://abhayporwals.hashnode.dev/how-i-tested-for-http-verb-tunneling-using-akto`
Twitter Post          -   `https://twitter.com/abhayporwals/status/1659147430250840065?s=20` 
LinkedIn Post       -    `https://www.linkedin.com/posts/theabhayporwal_how-i-tested-for-http-verb-tunneling-using-activity-7064913759701483520-GcKs?utm_source=share&utm_medium=member_desktop`

**Comment by Ankita28g** [comment]
Awesome! thanks abhay. reviewing these

**Comment by professorabhay** [comment]
Sure !! 
Is there any update on the form link ?? 
I didn't recieve any....
And issue is still showing open 😶

**Comment by Ankita28g** [comment]
Yes. you have created two blogs. Thank you so much! you will be getting your prizes soon. please join discord for all prize discussions

verb tunneling- https://abhayporwals.hashnode.dev/how-i-tested-for-http-verb-tunneling-using-akto
inventory: https://abhayporwals.hashnode.dev/how-to-create-automated-inventory-using-akto

**Comment by Ankita28g** [comment]
@professorabhay  Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by professorabhay** [comment]
Sure !! 
Thankyou so much 
Looking ahead for more contributions !! ✨
