### ISSUE TITLE
📃 Write a blog post about JWT None algo attack using Akto

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#147]
# 💭 Introduction

Akto is an open source API security product. 

Your task is to write a blog post about testing for `JWT None Algo attack `using Akto.

###  🎯 Requirements

- Your article has to be publicly available.
- Your article must tag Akto in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task summary:

- [ ] Drop a comment on this issue indicating that you’re working on it.
- [ ] Write a blog post with title  `How I tested for JWT None Algo attack using Akto?` [Test](https://github.com/akto-api-security/tests-library/blob/master/Broken%20Function%20Level%20Authorization/business-logic/AddMethodInParameterTest.java)
- [ ] Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ] Submit a pull request here.
- [ ] Share your work on social media and tag https://github.com/akto-api-security/akto (Reddit / HackerNews / Twitter / Facebook / Linkedin)

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by Aviraltech** [comment]
@Ankita28g  I would like to work on this issue please assign it to me.

**Comment by Ankita28g** [comment]
Hi @Aviraltech thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by aayushii9602** [comment]
This looks interesting too!!
how about you assign me this?

**Comment by beneyalraj** [comment]
i would like to work on this

**Comment by Ankita28g** [comment]
@aayushii9602 and @beneyalraj assigned to both of you

**Comment by beneyalraj** [comment]
I've published a blog please let me know if its good

**Comment by avneesh-akto** [comment]
@beneyalraj the blog looks good to me. 

Some suggestions to make it better:

1. In Step 2 (Identifying the Target Endpoint) it is not necessary to use PUT endpoint. Instead talk how to target endpoints with JWT token in request
2. In Step 6 (Check the Attempt Tab for the Modified Token) hover on the "authorization" header to show how the token has changed. Maybe use jwt.io to show the none algorithm in the new token
3. Talk about https://www.akto.io/test/jwt-none-algorithm in your blog. Akto has test library where anyone can test their API for JWT none algo vulnerability without signing up on Akto and highlight the simplicity of the approach

Make these changes and we are pretty much good to go.

**Comment by beneyalraj** [comment]
I have made the above changes in the blog post

**Comment by avneesh-akto** [comment]
This looks awesome @beneyalraj. @Ankita28g can you also review this.
