### ISSUE TITLE
📃 Write a blog post about testing for JWT invalid signature using Akto

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#148]
# 💭 Introduction

Akto is an open source API security product. 

Your task is to write a blog post about testing for `JWT invalid signature`using Akto.

###  🎯 Requirements

- Your article has to be publicly available.
- Your article must tag Akto in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task summary:

- [ ] Drop a comment on this issue indicating that you’re working on it.
- [ ] Write a blog post with title  `How I tested for JWT invalid signature using Akto?`
- [ ] Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ] Submit a pull request here.
- [ ] Share your work on social media and tag https://github.com/akto-api-security/akto (Reddit / HackerNews / Twitter / Facebook / Linkedin)

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by legendary0911** [comment]
I would like to work on it

**Comment by notshivansh** [comment]
Sure, @legendary0911 . Assigning it to you.

**Comment by Ankita28g** [comment]
Hi @legendary0911 thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by beneyalraj** [comment]
i would like to work on this

**Comment by avneesh-akto** [comment]
@beneyalraj Blog LGTM. Good memes.

Some suggestions:

1. In the intro, where you explain JWT maybe add a screenshot of how a typical jwt looks like. You can get that from jwt.io
2. Can you format the steps headlines (make it bolder)
3. In the intro itself can you talk about recent attacks that were carried out using invalid JWT signature

**Comment by beneyalraj** [comment]
Sure will make the changes

**Comment by avneesh-akto** [comment]
Awesome. LGTM. @Ankita28g this can be marked resolved

**Comment by Nupoor10** [comment]
Hello, Can I work on this?
