### ISSUE TITLE
📃 Write a blog post about testing for Security misconfiguration - open redirect using Akto

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#149]
# 💭 Introduction

Akto is an open source API security product. 

Your task is to write a blog post about testing for `Open Redirect`using Akto.

###  🎯 Requirements

- Your article has to be publicly available.
- Your article must tag Akto in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task summary:

- [ ] Drop a comment on this issue indicating that you’re working on it.
- [ ] Write a blog post with title  `How I tested for Open redirect using Akto?`
- [ ] Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ] Submit a pull request here.
- [ ] Share your work on social media and tag https://github.com/akto-api-security/akto (Reddit / HackerNews / Twitter / Facebook / Linkedin)

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by Abhishek2262** [comment]
Can I write this blog ?

**Comment by Ankita28g** [comment]
Hi @Abhishek2262 thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by Abhishek2262** [comment]
Yes

**Comment by Ankita28g** [comment]
can you share the link here please?

**Comment by Ankita28g** [comment]
@Abhishek2262  Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by Ankita28g** [comment]
This task can have multiple assignees.

**Comment by beneyalraj** [comment]
I would like to work on this please

**Comment by beneyalraj** [comment]
I've wrote a blog post on this issue 
https://medium.com/@beneyalraj03/how-i-tested-for-open-redirect-using-akto-f424d0fe5a7a

**Comment by avneesh-akto** [comment]
@beneyalraj Blog looks good to me. Loved the memes.

Some suggestions

1. Step 1 (Selecting the API Collection for Testing). Talk about which kind of APIs should be preferred to be tested. In case of open redirect vulnerability it's the 302 response APIs
2. Talk about https://www.akto.io/test/open-redirect in your blog. Akto has test library where anyone can test their API for Open Redirect vulnerability without signing up on Akto and highlight the simplicity of the approach

Make these changes and we are pretty much good to go.

**Comment by beneyalraj** [comment]
Thank you :) I have made the changes

**Comment by avneesh-akto** [comment]
Thank you for making the changes. LGTM. @Ankita28g this issue can you also review this
