### ISSUE TITLE
📃 Write a blog post about detecting sensitive data using Akto

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#168]
# 💭 Introduction

Akto is an open source API security product. 

Your task is to write a blog post about testing for `detecting sensitive data`using Akto.

###  🎯 Requirements

- Your article has to be publicly available.
- Your article must tag Akto in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task summary:

- [ ] Drop a comment on this issue indicating that you’re working on it.
- [ ] Write a blog post with title  `How I detected APIs leaking sensitive data using Akto?`
- [ ] Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ] Submit a pull request here.
- [ ] Share your work on social media and tag https://github.com/akto-api-security/akto (Reddit / HackerNews / Twitter / Facebook / Linkedin)

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Roshani9731** [comment]
@Ankita28g I would like to work on this issue please assign it to me.

**Comment by Dhruv9731** [comment]
@Ankita28g Me and @Roshani9731 would like to work together please assign us.

**Comment by Ankita28g** [comment]
So awesome to see you interest 🥳. Assigning to you! Happy hackfesting🎉

**Comment by Hrishikesh332** [comment]
Testing for sensitive data sounds familiar to me and it would be really great to advocate about the same. I would like to work on this issue, could you please assign me.

**Comment by Ankita28g** [comment]
Assigning it to you! Happy hackfesting 😃

**Comment by Ankita28g** [comment]
Assigned to you @Sa24miksha 

Happy hacktoberfest 😀😃

**Comment by Sa24miksha** [comment]
@Ankita28g, thank you for assigning me this work. It was enjoyable to explore and write about Akto. Here is my blog that fulfills all the requirements: 
https://medium.com/@samikshayadaav/how-i-detected-apis-leaking-sensitive-data-using-akto-b8e700bcac01

also the social media link : https://x.com/Samiksh2431/status/1712083399199052261?s=20

**Comment by Sa24miksha** [comment]
@Ankita28g @ankush-jain-akto please review it .

**Comment by Ankita28g** [comment]
@Sa24miksha I reviewed and left comment in Discord and LinkedIn message. Once it's corrected, you can resubmit

**Comment by Vishalk91-4** [comment]
@Ankita28g, can you assign this issue to me

**Comment by avneesh-akto** [comment]
I've assigned it to you, @Vishalk91-4 . Happy hacking! Feel free to join our [Discord](https://discord.com/channels/1070706429402562733/1095281477748543618) if you need assistance.

**Comment by MacroAndMicro** [comment]
@Ankita28g  can you please assign this issue to me? I would like to work on it.

**Comment by avneesh-akto** [comment]
I've assigned it to you, @MacroAndMicro  . Happy hacking! Feel free to join our [Discord](https://discord.com/channels/1070706429402562733/1095281477748543618) if you need assistance.

**Comment by Sath-vik23** [comment]
I would like to work on this issue, please assign it to me.
