### ISSUE TITLE
🧑🏻‍🏫 Create a tutorial about how to create API inventory using traffic mirroring

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#169]
# 💭 Introduction

Akto is an open source API security product. 

Your task is to create a video tutorial or written tutorial for `Create API inventory using traffic mirroring` in Akto.

###  🎯 Requirements

- Your readme file has to be publicly available.
- Your tutorial should have all the steps and look nice with description, titles, screenshots, videos or even memes. 

### ✅ Task summary:

- [ ] Drop a comment on this issue indicating that you’re working on it.
- [ ] Create a readme tutorial with title `[Tutorial] How to create automated API inventory using traffic mirroring in Akto?`
- [ ] Add it to this [repo](https://github.com/akto-api-security/30-API-security-tests).
- [ ] Submit a pull request here.
- [ ] Share your work on social media and tag https://github.com/akto-api-security/akto (Reddit / HackerNews / Twitter / Facebook / Linkedin)

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
Assigned to you @professorabhay. Happy Hackfesting 🔥

**Comment by professorabhay** [comment]
Hey @Ankita28g, I tried to resolve it.  `https://github.com/akto-api-security/30-API-security-tests/pull/1`
Please look into it and give me your reviews.
Like It is correct or need modifications.....

**Comment by Ankita28g** [comment]
Thanks @professorabhay. Approved but I will make some changes to it. Thank you for your contribution!
