### ISSUE TITLE
Automate product releases on discord

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#212]
# 💭 Introduction
Akto has a discord channel where we want all the release notes to be automated from GitHub.

###  🎯 Requirements

- Understanding of Discord
- Understanding of github actions

### ✅ Task summary

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Use this [GitHub Action](https://github.com/marketplace/actions/discord-styled-releases-patch-notes) to automate release notes to Discord.
- [ ] You will need Discord's API key. Use webhooks server [integrations](https://support.discord.com/hc/en-us/articles/360045093012-Server-Integrations-Page). 
- [ ] Please get the workflow working using your API key. Please don't expose your key in code. use secret variables.
- [ ] Submit PR here. We will put our API discord server's key under the name `DISCORD_API_KEY`.

### 🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Prixix** [comment]
Hey, can I work on this issue?

**Comment by Ankita28g** [comment]
hi @Prixix assigned to you the issue! Happy hackfesting 🎉

**Comment by siddoinghisjob** [comment]
Hey I want to work on this! Can I be assigned?

**Comment by Ankita28g** [comment]
hi @siddoinghisjob , this issue is already assigned. We've created a similar [issue](https://github.com/akto-api-security/akto/issues/236) for you. commenting you there. 🙏

**Comment by Ankita28g** [comment]
Thank you so much for the contribution! The changes have been merged 👍

**Comment by Ankita28g** [comment]
Thank you so much for the contribution! The changes have been merged. ❤️

**Comment by Ankita28g** [comment]
@Prixix  Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by Ankita28g** [comment]
Hi @Prixix let me know once you are done adding details. thanks
