### ISSUE TITLE
Automate product releases on beamer

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#236]
# 💭 Introduction
Akto release updates goes through [beamer](https://app.getbeamer.com/login) to all users. We want all the release notes to be automated from GitHub to beamer.

###  🎯 Requirements

- Understanding of [beamer](https://www.getbeamer.com/) and API.
- Understanding of github actions

### ✅ Task summary

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Unfortunately, we couldn't find a GitHub action to send updates to Beamer directly. You can either find one, create your own or directly add `curl` API call to a workflows file.
- [ ] You will need Beamer API key. You can get it via a secret var `BEAMER_API_KEY`.
- [ ] Create a Beamer account and please get the workflow working using your API key. Please don't expose your key in code. Use secret variables.
- [ ] Submit PR here. We will put our API Beamer key under the name `BEAMER_API_KEY`.

### 🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
hi @siddoinghisjob 👋

**Comment by siddoinghisjob** [comment]
Hi! Can you please assign me this issue?

**Comment by Ankita28g** [comment]
Assigned! Happy hackfesting 🎉

**Comment by Ankita28g** [comment]
Hi @siddoinghisjob Thank you so much for your contribution! 🤘🏻 your PR had been merged. Looking forward to see the automated release on beamer now 😃

**Comment by Ankita28g** [comment]
@siddoinghisjob Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by Ankita28g** [comment]
let me know once done @siddoinghisjob

**Comment by siddoinghisjob** [comment]
@Ankita28g done 👍
