### ISSUE TITLE
⚡️ Add sensitive data type related to insurance

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#93]
# 💭 Introduction

Akto allows users to find sensitive params in request and response of APIs. These sensitive params include PII data such as SSN, Credit card number, phone number etc. You can check how it works in the [docs](https://docs.akto.io/api-inventory/sensitive-data).

Your task is to add sensitive params related to `Insurance`.

###  👀 Impact

Your task will give users the ability to detect `insurance` related sensitive data types.

###  🎯 Requirements

- Understanding of regex
- Understanding of unit test

### ✅ Task summary

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Make regular expressions for below 7 insurance-related types. Feel free to add your own too.
- [ ] Please mention reference URL for each pattern (where it clearly mentions the nature of the identification number)
- [ ] Add an entry in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json) file
- [ ] Add a test case entry in [TestFintechTypes.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java#L32)
- [ ] Submit a pull request here 

```
US Medicare Health insurance claim number (HICN)
Indian Unique Health Identification (UHID) . Reference [example](https://www.bajajfinservhealth.in/articles/uhid-number)
United Kingdom National Insurance number
Finnish personal identity number for health insurance
Canadian Social Insurance Number (SIN) number
German insurance identity numbers
Japanese social insurance number
```

### ✌🏻 Hints

Example for Indian Unique Health Identification (UHID) . 
- Reference [example](https://www.bajajfinservhealth.in/articles/uhid-number)

### 🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by rajaryan18** [comment]
Can I be assigned to this issue? Thank You

**Comment by Ankita28g** [comment]
Sure @rajaryan18 assigning to you! happy hackfesting 🎊

**Comment by rajaryan18** [comment]
Hey, where do I mention the links to the source of information?

**Comment by ankush-jain-akto** [comment]
Hi @rajaryan18 

You can simply add a comment here or you can put a comment in your PR as well.

**Comment by Ankita28g** [comment]
Hi @rajaryan18  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by Ankita28g** [comment]
Did you finally submit the PR @rajaryan18 ?

**Comment by rajaryan18** [comment]
Yes I did submit the PR in the form. Should I submit it again?

**Comment by Ankita28g** [comment]
no found it. thank you. Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by rajaryan18** [comment]
Could you tell me approximately how long will it take for the swags to be delivered? I'm in Bangalore now but I'll be going back to hostel (Ranchi) in mid July. So accordingly I'll add the details. Thank you.

**Comment by Ankita28g** [comment]
you will have it by June
