### ISSUE TITLE
⚡️Add sensitive data type for fintech

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#94]
# 💭 Introduction
Akto allows users to find sensitive params in request and response of APIs. These sensitive params include PII data such as SSN, Credit card number, phone number etc. You can check how it works in the [docs](https://docs.akto.io/api-inventory/sensitive-data).

Your task is to add sensitive params related to `fintech`.

###  👀 Impact: 

Your task will give users the ability to detect sensitive data types  related to `fintech`.

### 🎯 Requirements:

- Understanding of regex
- Understanding of unit test

### ✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Make regular expressions for below fintech-related types. Feel free to add your own too.
- [ ] Please mention reference URL in the comments for each pattern (where it clearly mentions the nature of the identification number)
- [ ] Add an entry in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json) file
- [ ] Add a test case entry in [TestFintechTypes.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java#L32)
- [ ] Submit a pull request here 

```
International bank account number (IBAN).
Bank routing number.
United Kingdom individual taxpayer identification number (UTR).
United States bank account number.
United States individual taxpayer identification number (ITIN).
Indian permanent account number (PAN) assigned by the Income Tax Department.
Indian tax deduction account number or tax collection account number (TAN) assigned by the Income Tax Department.
Australian bank account number.
Australian bank branch (BSB) number.
Australian tax file number (TFN).
Austrian individual taxpayer identification number.
Austrian value added tax number (MWSt).
Brazilian individual taxpayer identification number.
Canadian bank routing number.
French value added tax number (VAT).
Debit card number used by major banks in the European Union.
German tax identity numbers (Steuer-ID).
German value added tax number (MWSt).
Israeli bank account number.
Italian value added tax number (IVA).
Japanese bank account number.
New Zealander bank account number.
New Zealander taxpayer identification number (IRD).
Portuguese individual taxpayer identification number (NIF).
Spanish individual taxpayer identification number (NIF).
```

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by catchingknives** [comment]
Some regexes for European PII can be found [here](https://github.com/mmcatcd/pii-tool/blob/master/European%20RegEx.csv)

**Comment by danm364** [comment]
Hi All, may I be assigned to the issue?

**Comment by Ankita28g** [comment]
Which one @danm364 ?

1. The one you commented on [Fintech](https://github.com/akto-api-security/akto/issues/94)
2. or [Europe specific](https://github.com/akto-api-security/akto/issues/130)

**Comment by Ankita28g** [comment]
Hi @danm364 Thanks for your interest 🙏 

Assigned you to the issue. Happy hackfesting 🥳

**Comment by Ankita28g** [comment]
Hi @danm364 are you working on this?

**Comment by Ankita28g** [comment]
Hi @danm364 how is it going? do you need help?

**Comment by danm364** [comment]
Hi @Ankita28g been mia the past few days i will be able to work on this tonight was referring to this one https://github.com/akto-api-security/akto/issues/94

**Comment by Ankita28g** [comment]
No worries at all 👍🏻 let me know if I can help.

**Comment by danm364** [comment]
For the IBAN numbers there are 94 separate ones of varying lengths. Guessing well need to create individual regex expressions for each one? 

https://www.swift.com/swift_resource/9606

**Comment by danm364** [comment]
They are similar just have the same country identifier rest of it is just different lengths

**Comment by danm364** [comment]
UK has two TIN like numbers - unique taxpayer reference (UTR) and national insurance number (NINO), possible also a Temporary reference number (TRN)
 https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/UK-TIN.pdf

**Comment by danm364** [comment]
https://www.swift.com/swift_resource/9606 - IBAN number for Andorra

**Comment by ankush-jain-akto** [comment]
Hi @danm364 

The Swift resource is really awesome! For this issue's purpose, you can add only the ones mentioned. If you feel doing more, add remaining countries as well. Me and my team will anyway make use of the Swift PDF and add all countries (post Hackathon)

**Comment by danm364** [comment]
I'm not very familiar with testing but i did add a few things to the fintech.json file. Idk if you could lead me to a tutorial on this maybe but a little lost there.

**Comment by ankush-jain-akto** [comment]
Hi @danm364 

I hear you. We are preparing 1-click code setup of Akto repo in a laptop (using VSCode & Intellij). Should be ready soon. 

In the meantime - 

1. Please prepare the PR with the regex entry added in the file
2. Add an example value that should match the regex. You can just put it here in the comments.

**Comment by ankush-jain-akto** [comment]
Hi @danm364 

Hope all is fine. Let us know if you need any help.

**Comment by Ankita28g** [comment]
Hi @danm364 do you need help with this?

**Comment by danm364** [comment]
Hi Sorry I may not get to work on it for a while, I'll try to jump in when possible

**Comment by Ankita28g** [comment]
Hi @danm364 no worries. whenever you are ready! we are here :) and happy to help if you need.

**Comment by Ankita28g** [comment]
Hi @Gonent @danm364  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!
