### ISSUE TITLE
⚡️Add sensitive data types - US specific

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#95]
# 💭 Introduction

Akto allows users to find sensitive params in request and response of APIs. These sensitive params include PII data such as SSN, Credit card number, phone number etc. You can check how it works in the [docs](https://docs.akto.io/api-inventory/sensitive-data).

Your task is to add US specific sensitive params.

###  👀 Impact

Your task will give users the ability to detect `US specific` sensitive data types.

###  🎯 Requirements

- Understanding of regex
- Understanding of unit test

### ✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Make regular expressions for below US-related types. Feel free to add your own too.
- [ ] Please provide the reference URL that mentions the nature of the number. 
- [ ] Add an entry in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json) file
- [ ] Add a test case entry in [TestFintechTypes.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java#L32)
- [ ] Submit a pull request here 

```
US Bank Account Number
US Individual Taxpayer Identification Number (ITIN).
US DEA Number - Federally authorized number assigned to health care providers.
US Health Insurance Claim Number - Medicare Health insurance claim number (HICN).
US Medicare Beneficiary Identifier - Medicare beneficiary identifier (MBI) number.
United States driver's license number.
United States passport number.
United States social security number (SSN).
```

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by legendary0911** [comment]
Can I be assigned this ?

**Comment by Ankita28g** [comment]
hi @legendary0911 assigning this to you! Happy hackfesting 🎉

**Comment by Ankita28g** [comment]
Hi @legendary0911  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!
