### ISSUE TITLE
⚡️Add sensitive data types file extension types

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#96]
# 💭 Introduction

Akto allows users to find sensitive params in request and response of APIs. These sensitive params include PII data such as SSN, Credit card number, phone number etc. You can check how it works in the [docs](https://docs.akto.io/api-inventory/sensitive-data).

Your task is to add `file extension types` in sensitive params.

###  👀 Impact

Your task will give users the ability to detect `file extension types` related sensitive data types.

###  🎯 Requirements

- Understanding of regex
- Understanding of unit test

### ✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Make regular expressions for below file types.
- [ ] Add an entry in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json) file
- [ ] Add a test case entry in [TestFintechTypes.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java#L32)
- [ ] Submit a pull request here  

`images - png/jpg/jpeg/svg, 
filetype: pdf/js/css/woff/txt
`
### 🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by TheSpeedX** [comment]
Hey @Ankita28g, I want to pickup this issue. Can you assign this to me ?

**Comment by Ankita28g** [comment]
Hi @TheSpeedX assigning to you! Happy hackfesting 😃

**Comment by TheSpeedX** [comment]
The issue description says to add this in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json). I don't think it will be the best place to add a file types in it. Should I create a `filetypes.json` instead and do relevant changes in InitializerListener ?

@Ankita28g  @ankush-jain-akto

**Comment by ankush-jain-akto** [comment]
Hi @TheSpeedX 

Totally. I thought I will do it later. But sure go ahead. 

Sorry, the code could be a bit messy there. Lmk. I can improve it.

**Comment by Ankita28g** [comment]
Hi @TheSpeedX do you need help with the issue?

**Comment by TheSpeedX** [comment]
Hey sorry was a bit occupied with other stuff, will update this today

**Comment by Ankita28g** [comment]
Hi @TheSpeedX  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!
