### ISSUE TITLE
⚡️Add sensitive data types US addresses

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#97]
# 💭 Introduction

Akto allows users to find sensitive params in request and response of APIs. These sensitive params include PII data such as SSN, Credit card number, phone number etc. You can check how it works in the [docs](https://docs.akto.io/api-inventory/sensitive-data).

Your task is to add US addresses as sensitive params.

###  👀 Impact

Your task will give users the ability to detect `US addresses` sensitive data types.

###  🎯 Requirements

- Understanding of regex
- Understanding of unit test

### ✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Make regular expressions for US address. 
- [ ] Please provide the reference URL that mentions the nature of the address. 
- [ ] Add an entry in [fintech.json](https://github.com/akto-api-security/akto/blob/master/pii-types/fintech.json) file
- [ ] Add a test case entry in [TestFintechTypes.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/test/java/com/akto/listener/TestFintechTypes.java#L32)
- [ ] Submit a pull request here 

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
Hi @marksowell, assigned to you! Happy Hackfesting 🎉

**Comment by marksowell** [comment]
- Reference URL - https://docs.opswat.com/mdcore/proactive-dlp/sample-regular-expressions
- Submitted PR  #225

**Comment by Ankita28g** [comment]
Thanks a lot @marksowell, your PR is under review!

**Comment by Ankita28g** [comment]
Hi @marksowell  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!
